name: GitHub Profile Update

on:
  push:
    branches:
      - main
  schedule: 
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit and push files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Actions" 
          author_email: "actions@github.com"
          message: "Update Profile Summary"
          add: "."
          push: "https://github.com/ankitT20/ankitT20.git"